INTERESTS = ('(AI OR '
             '"artificial intelligence" OR '
             '"machine learning" OR '
             '"generative AI" OR '
             'LLM OR cybersecurity OR '
             '"cyber security" OR '
             'cyberattack OR '
             '"data breach" OR '
             'ransomware OR '
             'malware OR '
             'hacking OR '
             'phishing OR '
             'vulnerability OR '
             '"video games" OR '
             'gaming OR '
             '"game development" OR '
             'hardware OR '
             '"graphics card" OR '
             'GPU OR '
             'CPU OR '
             '"PC components" OR '
             '"tech industry" OR '
             'IT OR '
             '"new movies" OR '
             'movies OR'
             '"movie releases" OR '
             '"upcoming films" OR '
             'actors OR '
             '"actor interviews" OR '
             '"celebrity interviews" OR '
             '"good music" OR '
             '"music releases" OR '
             '"new album" OR '
             'music OR '
             'rock OR '
             'festivals OR '
             '"music festivals" OR '
             'camping OR '
             'mountain OR'
             'animals OR'
             'pets' 
             ')')
