INTERESTS = ('(AI OR '
             'LLM OR '
             'cybersecurity OR '
             'cyberattack OR '
             'ransomware OR '
             'malware OR '
             'hacking OR '
             'phishing OR '
             'vulnerability OR '
             'gaming OR '
             'hardware OR '
             'GPU OR '
             'CPU OR '
             'IT OR '
             'movies OR '
             'actors OR '
             'music OR '
             'rock OR '
             'festivals OR '
             'camping OR '
             'mountain OR '
             'animals OR '
             'pets OR '
             'fitness OR '
             'gym OR '
             'nutrition)')
